### ISSUE TITLE
Unable to download images

### ISSUE THREAD

**Issue by shobhit-kumar-code** [tzutalin/ImageNet_Utils#17]
On executing 
./downloadutils.py --downloadOriginalImages --wnid n03412511
i get an error message: 

Traceback (most recent call last):
  File "downloadutils.py", line 54, in <module>
    downloader.downloadOriginalImages(id, username, accessKey)
  File "./libs/imagedownloader.py", line 120, in downloadOriginalImages
UnboundLocalError: local variable 'download_file' referenced before assignment

**Comment by chexianghong** [comment]
Have you solved your issue? I have the same bug as you

**Comment by shobhit-kumar-code** [comment]
I could not find a way around. But what i did was that i created an account on ImageNet. After that, you need to get access to download from ImageNet directly. After that a download button is visible whenever you view something on ImageNet
Although, i think this issue is with your account. You either need to create one or get download access.

![untitled](https://user-images.githubusercontent.com/22573271/50343128-cce8b680-054b-11e9-832e-665297514dd1.jpg)

**Comment by chexianghong** [comment]
I also can down load images and bounding box files, but there is not a one
to one relation between images and bounding box. Could you figure it out?

Shobhit Kumar <notifications@github.com> 于2018年12月21日周五 下午8:51写道：
