### ISSUE TITLE
IOError occurs when trying to download with python downloadutils.py --downloadImages --wnid n03492922

### ISSUE THREAD

**Issue by bit-scientist** [tzutalin/ImageNet_Utils#18]
I am following the steps on Windows 10 and I think there is something I should change.
When I run `python downloadutils.py --downloadImages --wnid n03492922` in _D:\dataset\safet_helmet_dataset\ImageNet_Utils>_ I have the below error
```
Traceback (most recent call last):
  File "downloadutils.py", line 34, in <module>
    list = downloader.getImageURLsOfWnid(id)
  File "./libs\imagedownloader.py", line 78, in getImageURLsOfWnid
    f = urllib.urlopen(url)
  File "C:\Users\sohib\Anaconda3\envs\py27\lib\urllib.py", line 87, in urlopen
    return opener.open(url)
  File "C:\Users\sohib\Anaconda3\envs\py27\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Users\sohib\Anaconda3\envs\py27\lib\urllib.py", line 351, in open_http
    errcode, errmsg, headers = h.getreply()
  File "C:\Users\sohib\Anaconda3\envs\py27\lib\httplib.py", line 1196, in getreply
    response = self._conn.getresponse()
  File "C:\Users\sohib\Anaconda3\envs\py27\lib\httplib.py", line 1121, in getresponse
    response.begin()
  File "C:\Users\sohib\Anaconda3\envs\py27\lib\httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "C:\Users\sohib\Anaconda3\envs\py27\lib\httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\Users\sohib\Anaconda3\envs\py27\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
IOError: [Errno socket error] [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```
What would you suggest doing?
Thank you!

**Comment by vinamramattoo** [comment]
Getting the following error
python downloadutils.py --downloadImages --wnid n03492922
 ```
 File "downloadutils.py", line 21
    print 'No wnid'
                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('No wnid')?
```
